site_name: Kaleido Subtitling Handbook
site_description: A comprehensive handbook for Kaleido's best subtitling practices
site_author: Kaleido-subs
site_url: https://kaleido-subs.github.io/handbook/guidelines
repo_url: https://github.com/Kaleido-subs/handbook

theme:
  name: material
  language: en
  palette:
    primary: purple
    accent: indigo
    scheme: slate
  features:
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.footer
    - toc.follow
    - toc.integrate

nav:
  - Home: index.md
  - Group:
    - Index: group/index.md
    - Roles: group/roles.md
    - Distribution: group/distribution.md
  - Roles:
    - Index: roles/index.md
    - Translation: roles/translation.md
    - Editing: roles/editing.md
    - Timing: roles/timing.md
    - Typesetting: roles/typesetting.md
    - Song Styling: roles/songstyling.md
  - Technical:
    - Index: technical/index.md
    - Dialogue Styling: technical/dialogue-styling.md
    - Shenanigans: technical/shenanigans.md
    - Building Muxes:
      - Introduction: building/index.md
      - Getting Started: building/getting-started.md
      - Project Structure:
        - Introduction: building/structure/index.md
      - Subtitle Properties:
        - Structure: building/properties/index.md
      - Build Script:
        - Introduction: building/build-script/index.md
        - Tasks: building/build-script/tasks.md
  - Release:
    - Index: release/index.md
    - Description: release/description.md
  - Additional Resources:
    - Index: resources/index.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        import:
          - https://docs.python.org/3/objects.inv
        options:
          docstring_style: "sphinx"
          show_symbol_type_heading: true
          show_symbol_type_toc: true

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      pygments_style: "one-dark"
      noclasses: true
      linenums: true
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc
