site_name: The Kaleido Subtitling Style Handbook
site_description: A comprehensive guide for Kaleido's best subtitling practices
site_author: LightArrowsEXE
site_url: https://example.com
repo_url: https://github.com/Kaleido-subs/style-guide

theme:
  name: material
  language: en
  palette:
    primary: purple
    accent: indigo
    scheme: slate
  features:
    - content.code.copy
    - content.code.select
    - navigation.expand

nav:
  - Home: index.md
  - Group:
    - Roles: group/roles.md
  - Guidelines:
    - Dialogue Styling: guidelines/styling/dialogue_styling.md
    - Translation: guidelines/translation.md
    - Editing: guidelines/editing.md
    - Timing: guidelines/timing.md
    - Shenanigans: guidelines/shenanigans.md
    - Song Styling: guidelines/styling/songstyling.md
    - Typesetting: guidelines/typesetting.md
    - Technical: guidelines/technical.md
  - Building:
    - Introduction: building/index.md
    - Getting Started: building/getting-started.md
    - Project Structure:
      - Introduction: building/structure/index.md
    - Subtitle Properties:
      - Structure: building/properties/index.md
    - Build Script:
      - Introduction: building/build-script/index.md
      - Tasks: building/build-script/tasks.md
  - Release:
    - Description: release/description.md
  - Additional Resources: resources.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        import:
          - https://docs.python.org/3/objects.inv
        options:
          docstring_style: "sphinx"
          show_symbol_type_heading: true
          show_symbol_type_toc: true

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      pygments_style: "one-dark"
      noclasses: true
      linenums: true
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
