site_name: The Kaleido Subtitling Style Handbook
site_description: A comprehensive guide for Kaleido's best subtitling practices
site_author: LightArrowsEXE
site_url: https://example.com
repo_url: https://github.com/Kaleido-subs/style-guide

theme:
  name: material
  language: en
  palette:
    primary: purple
    accent: indigo
    scheme: slate
  features:
    - content.code.copy
    - content.code.select
    - navigation.expand

nav:
  - Home: index.md
  - Group:
    - Roles: group/roles.md
  - Guidelines:
    - Dialogue Styling: guidelines/styling/dialogue_styling.md
    - Timing: guidelines/timing.md
    - Editing: guidelines/editing.md
    - Shenanigans: guidelines/shenanigans.md
    - Song Styling: guidelines/styling/songstyling.md
    - Technical: guidelines/technical.md
  - Additional Resources: resources.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        import:
          - https://docs.python.org/3/objects.inv
        options:
          docstring_style: "sphinx"
          show_symbol_type_heading: true
          show_symbol_type_toc: true

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      pygments_style: "one-dark"
      noclasses: true
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
